name = "safetrain-api"
main = "src/server.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# [vars]
# MY_VARIABLE = "production_value"

[[d1_databases]]
binding = "DB"
database_name = "safetrain-d1"
database_id = "cf659bc9-c579-4552-bb75-6eeaa3940d6a"
